dist: bionic
language: go
go:
- 1.14.x
env:
- TRAVIS=true PROCJON_SLACK_WEBHOOK=https://slack.com/api/api.test
script: 
- ./.test.sh
before_script:
- ./.cert_gen.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)