# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- binary: procjon
  id: procjon
  main: ./server/procjon.go
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - 7
- binary: procjonelastic
  id: procjonelastic
  main: ./elastic/procjonelastic.go
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - 7
- binary: procjonsystemd
  id: procjonsystemd
  main: ./systemd/procjonsystemd.go
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - 7
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
    - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
